name: Auto-merge Codex PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, ready_for_review]

jobs:
  automerge:
    if: github.event.pull_request.labels.*.name contains 'codex' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Codex PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Merge PR if possible
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request: ${{ github.event.pull_request.number }}
          required-approval-count: 0
